// "System Requirements → first-cut model" modal (DIAG-37). Import a .md/.txt file
// or paste requirements text, then Generate — the parent calls the configured
// provider endpoint, normalizes + applies the returned model, and the result is a
// DRAFT to refine in the studio (never a source of truth). Requirements text lives
// in modal-local state only, so it never bloats the persisted/recovery model.
import React, { useState } from 'react';
import { useTheme } from './ThemeContext';

export default function RequirementsModal({ onGenerate, onClose }) {
  const { endpointUrl } = useTheme();
  const [text, setText] = useState('');
  const [fileName, setFileName] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const [notes, setNotes] = useState(null); // success step: low-confidence notes to confirm

  const onFile = async (e) => {
    const f = e.target.files?.[0];
    if (!f) return;
    setFileName(f.name);
    try { setText(await f.text()); } catch (err) { setError(`Could not read ${f.name}: ${err?.message || err}`); }
  };

  const generate = async () => {
    setError(null); setNotes(null); setBusy(true);
    try {
      const result = await onGenerate(text); // parent: call provider → normalize → confirm-replace → apply
      if (result?.cancelled) { setBusy(false); return; } // user declined the replace confirm
      setNotes(result?.notes || []);
    } catch (err) {
      setError(err?.message || String(err));
    } finally {
      setBusy(false);
    }
  };

  const canGenerate = text.trim().length > 0 && !busy;

  return (
    <div className="atlas-modal-backdrop" onClick={busy ? undefined : onClose}>
      <div className="atlas-modal" onClick={(e) => e.stopPropagation()}>
        <h2>Generate a model from requirements</h2>

        {notes ? (
          // ── Success step ──
          <>
            <p className="atlas-empty">
              A first-cut model was generated and applied. It’s a <strong>draft to refine</strong> —
              check it in the studio, fill any gaps, and confirm the inferences below.
            </p>
            {notes.length > 0 ? (
              <>
                <label>To confirm:</label>
                <div className="atlas-delete-list">
                  {notes.map((n, i) => <div key={i}>• {n}</div>)}
                </div>
              </>
            ) : <p className="atlas-empty">No low-confidence inferences were flagged.</p>}
            <div className="atlas-modal-actions">
              <button onClick={onClose}>Refine in studio</button>
            </div>
          </>
        ) : (
          // ── Input step ──
          <>
            <p className="atlas-empty">
              Import or paste your requirements. The model is generated by the endpoint set in
              Settings ({endpointUrl ? <code>{endpointUrl}</code> : <em>not configured — set it in Settings</em>}),
              then becomes an editable draft you ratify here. <strong>It replaces the current model.</strong>
            </p>

            <div className="atlas-modal-row">
              <label>Import a requirements file (.md / .txt)</label>
              <input type="file" accept=".md,.txt,text/plain,text/markdown" onChange={onFile} />
              {fileName && <div className="atlas-slider-sample">Loaded: {fileName}</div>}
            </div>

            <div className="atlas-modal-row">
              <label>…or paste requirements</label>
              <textarea
                value={text}
                onChange={(e) => setText(e.target.value)}
                rows={10}
                placeholder="Paste your SSDD / requirements here…"
                autoCapitalize="off" autoCorrect="off" spellCheck={false}
              />
            </div>

            {error && <div className="atlas-field-error">{error}</div>}

            <div className="atlas-modal-actions">
              <button className="atlas-slider-reset" onClick={onClose} disabled={busy}>Cancel</button>
              <button onClick={generate} disabled={!canGenerate} title={canGenerate ? 'Generate a first-cut model' : 'Add requirements text first'}>
                {busy ? 'Generating…' : 'Generate model'}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
